language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t heshamhayat/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true heshamhayat/react-test npm run test
after_success:
  - docker build -t heshamhayat/multi-client ./client
  - docker build -t heshamhayat/multi-nginx ./nginx
  - docker build -t heshamhayat/multi-server ./server
  - docker build -t heshamhayat/multi-worker ./worker
  # LOGIN TO DOCKER
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # PUSH IMAGES TO DOCKER
  - docker push heshamhayat/multi-client
  - docker push heshamhayat/multi-nginx
  - docker push heshamhayat/multi-server
  - docker push heshamhayat/multi-worker